/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include <stdint.h>
#include "main.h"


int main(void)
{
	//Enable the clock for the GPIO port using AHB1ENR register
	RCC_AHB1ENR volatile *rccahb1enr; // From the strcut
	rccahb1enr=(RCC_AHB1ENR*)0x40023830; // address of RCC
	rccahb1enr->gpioa_en =1;


	//Creating a pointer variable from the struct
	GPIOx_MODER volatile *pgpioaMode;
	pgpioaMode=(GPIOx_MODER*)0x40020000;
	pgpioaMode->pin_5=1; //configuring the Mode register as Ouput mode

	//creating the pointer variable from the struct for GPIO output register
	GPIOx_ODR volatile *pgpioaOutput;
	pgpioaOutput =(GPIOx_ODR*)0x40020014;

	//Accessing the pin
	while(1){


		for(int i=0;i<50000;i++)
		{
			pgpioaOutput->pin_5=0;
		}

		for(int i=0;i<50000;i++)
		{
			pgpioaOutput->pin_5=1;
		}

	}
}
