/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>



#define RCC_APB2_REG 				0x40023800UL								//Base address of RCC register
#define RCC_CFGR					0x08UL									//RCC_APB2ENR offset value
#define RCC_APB2_ADD				(RCC_APB2_REG + RCC_CFGR)
//RCC clock enable for GPIOA register
#define RCC_AHB1ENR_BASE_ADD		0x40023800
#define RCC_AHB1ENR_GPIOA_OFFSET	0x30
#define RCC_AHB1ENR_GPIOA_REG       (RCC_AHB1ENR_BASE_ADD + RCC_AHB1ENR_GPIOA_OFFSET )

//MAPING MCO1 IN GPIOA
#define GPIOA_BASE_ADD 				0x40020000UL
#define GPIOA_OFFEST				0x00
#define GPIOA_PORTMODE_REG			(GPIOA_BASE_ADD + GPIOA_OFFEST )

// Maping Alternate function register
#define GPIOA_AFRH_OFFSET_ADD	 	0x24 // Alternate function register
#define GPIOA_AFRH_ADD				(GPIOA_BASE_ADD + GPIOA_AFRH_OFFSET_ADD )

int main(void)
{
	uint32_t *pRccCfgreg = (uint32_t*)RCC_APB2_ADD;
	//Clearing BIT in MCO1
	*pRccCfgreg &= ~(0x3<<21);  //To clear bit using value 3 (clear 21 and 22 bit positions)
	//Set a BIT in MC01
	*pRccCfgreg |= (0x2<<21);	//To Set Bit using value 2   (set 21 and 22 bit positions)

	//Enable clock for GPIOA register
	uint32_t *pGPIOA =(uint32_t*)RCC_AHB1ENR_GPIOA_REG;
	*pGPIOA &= ~(0x1); //CLEARBIT
	*pGPIOA |= (0x1);  //SETBIT

	//Enable portmode Register as funcional output
	uint32_t *pportmodereg =(uint32_t*) GPIOA_PORTMODE_REG;
	*pportmodereg &= ~(0x3 <<16); //CLEARBIT
	*pportmodereg |= (0x2 <<16);

	//Enable Alternate functioin mode register in GPIOA PA8
	uint32_t *pgpioaAFRH = (uint32_t*)GPIOA_AFRH_ADD;
	*pgpioaAFRH &= ~(0xf<<0); //CLEAR BIT using 1111 in AFRH register to set AFO

	//Using prescalaer
	*pRccCfgreg |= (0x3<<24);




	for(;;);
}
